export const dynamic = 'force-dynamic';

import React from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';
import { ThemeProvider } from '@/components/ThemeContext';
import { ReduxProvider } from './store/providers';
import Providers from './queryProvider';
import ConfigureAmplifyClientSide from '@/components/ConfigureAmplify';
import Header from '@/components/Header';
import { StyleWrapper } from '@/components/StyleWrapper';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Fan Contest Hub',
	// description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ConfigureAmplifyClientSide />
				<ReduxProvider>
					<Providers>
						<ThemeProvider>
							<StyleWrapper>
								<Header />
								{children}
							</StyleWrapper>
							<Toaster />
						</ThemeProvider>
					</Providers>
				</ReduxProvider>
			</body>
		</html>
	);
}
